import Head from 'next/head';
import Router, { createRouter } from '../router';
import styles from '../styles/Home.module.css';
import { routes } from './routes';

export default function Home() {
  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <Router routers={createRouter(routes)} />
      </main>
    </div>
  );
}
